language: node_js

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - "docker build -t akosborn/personal-finance:${TRAVIS_BRANCH//\//\_}"
